name: kb_mobile_app
description: Mobile app for reporting OVC and AGYW cases unde KB project.
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2
  geolocator: ^6.0.0
  cupertino_icons: ^0.1.3
  uuid: ^2.2.0
  shared_preferences: ^0.5.10
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.0
  http: ^0.12.2
  random_color: ^1.0.5
  fluttertoast: ^7.0.4
  sqflite:
  path:
  flutter_stetho: ^0.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
